version: '3.7'

services:
  solace:
    container_name: public-solace-pubsub
    image: artifacts.bcp.absa.co.za/fx-trading-qa-docker-local/public-solace-pubsub:1.0
    shm_size: 1g
    ulimits:
      core: 1
      nofile:
        soft: 2448
        hard: 6592
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100
    ports:
      - 8008:8008
      - 1883:1883
      - 5672:5672
      - 8000:8000
      - 8080:8080
      - 1943:1943
      - 9000:9000
      - 55554:55554
      - 2222:2222
      - 55555:55555
      - 1443:1443 
      - 55443:55443
    volumes:
      - ./certs:/certs